#!/usr/bin/env python3
"""Generate the fixed-parameter, axis-regular Cartesian Kerr C evaluator."""

from __future__ import annotations

import argparse
import difflib
from pathlib import Path
import sys

import sympy as sp


ROOT = Path(__file__).resolve().parent
DEFAULT_OUTPUT = ROOT / "generated" / "kerr_exact.c"
DEFAULT_FIXTURES = ROOT / "generated" / "kerr_exact_fixtures.h"


def build_metric() -> tuple[tuple[sp.Symbol, ...], tuple[sp.Expr, ...]]:
    """Return coordinates and the ten stable independent metric components."""

    x, y, z = sp.symbols("x y z", real=True)
    radius_squared = x * x + y * y + z * z
    radius = sp.sqrt(radius_squared)

    mass = sp.Integer(1)
    spin = sp.Rational(1, 2)
    horizon_gap = sp.sqrt(3) / 2
    r_plus = mass + horizon_gap
    r_minus = spin**2 / r_plus
    throat = r_plus / 4

    # These cancellation-resistant auxiliaries are the Cartesian form checked
    # in kerr_notes.  In particular, Q never evaluates the small difference
    # R-r_- and D is formed directly rather than by subtracting B-L.
    p_factor = (radius - throat) ** 2 / radius
    q_factor = p_factor + 2 * horizon_gap
    boyer_radius = r_plus + p_factor
    sigma = boyer_radius**2 + spin**2 * z**2 / radius_squared
    ell = sigma / radius_squared
    dee = sigma * r_minus / (radius_squared * q_factor)
    cee = (
        spin**2
        * (sigma + 2 * mass * boyer_radius)
        / (sigma * radius_squared**2)
    )
    ache = (
        2 * mass * spin * boyer_radius / (sigma * radius_squared)
    )

    radial = (x, y, z)
    azimuthal = (-y, x, sp.Integer(0))
    gamma = sp.MutableDenseMatrix(3, 3, [sp.Integer(0)] * 9)
    for row in range(3):
        for column in range(3):
            gamma[row, column] = (
                (ell if row == column else 0)
                + dee * radial[row] * radial[column] / radius_squared
                + cee * azimuthal[row] * azimuthal[column]
            )

    components = (
        -(1 - 2 * mass * boyer_radius / sigma),
        ache * y,
        -ache * x,
        sp.Integer(0),
        gamma[0, 0],
        gamma[0, 1],
        gamma[0, 2],
        gamma[1, 1],
        gamma[1, 2],
        gamma[2, 2],
    )
    return (x, y, z), components


def c_expression(expression: sp.Expr) -> str:
    """Render one expression as deterministic C99."""

    return sp.ccode(expression, standard="C99")


def emit_cse(
    expressions: tuple[sp.Expr, ...], temporary_prefix: str
) -> tuple[list[str], list[str]]:
    """Return C declarations for CSE temporaries and reduced expressions."""

    replacements, reduced = sp.cse(
        expressions,
        symbols=sp.numbered_symbols(temporary_prefix),
        order="canonical",
    )
    declarations = [
        f"  const double {symbol} = {c_expression(expression)};"
        for symbol, expression in replacements
    ]
    return declarations, [c_expression(expression) for expression in reduced]


def generate_source() -> str:
    """Generate the complete C translation unit."""

    coordinates, values = build_metric()
    derivatives = tuple(
        sp.diff(value, coordinate)
        for value in values
        for coordinate in coordinates
    )
    value_declarations, value_outputs = emit_cse(values, "v")
    combined = tuple(
        item
        for component, value in enumerate(values)
        for item in (value, *derivatives[3 * component : 3 * component + 3])
    )
    gradient_declarations, gradient_outputs = emit_cse(combined, "j")

    assert len(values) == 10
    assert len(derivatives) == 30
    assert values[3] == 0
    assert derivatives[9:12] == (0, 0, 0)
    allowed_symbols = set(coordinates)
    for expression in (*values, *derivatives):
        assert expression.free_symbols <= allowed_symbols
        assert not expression.has(sp.Derivative)

    lines = [
        "/*",
        " * Generated by generate_kerr_exact.py; do not edit manually.",
        " * Fixed parameters: M=1, a=1/2.",
        " */",
        '#include "kerr_exact.h"',
        "",
        "#include <math.h>",
        "",
        "static int valid_coordinates(double x, double y, double z) {",
        "  const double radius_squared = x * x + y * y + z * z;",
        "  return isfinite(x) && isfinite(y) && isfinite(z) &&",
        "         isfinite(radius_squared) && radius_squared > 0.0;",
        "}",
        "",
        "kerr_exact_status kerr_exact_metric(",
        "    double x, double y, double z,",
        "    double values[KERR_EXACT_COMPONENT_COUNT]) {",
        "  double temporary[KERR_EXACT_COMPONENT_COUNT];",
        "",
        "  if (values == NULL) return KERR_EXACT_INVALID_ARGUMENT;",
        "  if (!isfinite(x) || !isfinite(y) || !isfinite(z))",
        "    return KERR_EXACT_INVALID_ARGUMENT;",
        "  if (!valid_coordinates(x, y, z)) return KERR_EXACT_DOMAIN_ERROR;",
        "",
        *value_declarations,
    ]
    lines.extend(
        f"  temporary[{index}] = {expression};"
        for index, expression in enumerate(value_outputs)
    )
    lines.extend(
        [
            "",
            "  for (size_t component = 0; component < KERR_EXACT_COMPONENT_COUNT;",
            "       ++component) {",
            "    if (!isfinite(temporary[component]))",
            "      return KERR_EXACT_NONFINITE_RESULT;",
            "  }",
            "  for (size_t component = 0; component < KERR_EXACT_COMPONENT_COUNT;",
            "       ++component) {",
            "    values[component] = temporary[component];",
            "  }",
            "  return KERR_EXACT_SUCCESS;",
            "}",
            "",
            "kerr_exact_status kerr_exact_metric_gradient(",
            "    double x, double y, double z,",
            "    kerr_exact_value_gradient results[KERR_EXACT_COMPONENT_COUNT]) {",
            "  double temporary[KERR_EXACT_COMPONENT_COUNT][4];",
            "",
            "  if (results == NULL) return KERR_EXACT_INVALID_ARGUMENT;",
            "  if (!isfinite(x) || !isfinite(y) || !isfinite(z))",
            "    return KERR_EXACT_INVALID_ARGUMENT;",
            "  if (!valid_coordinates(x, y, z)) return KERR_EXACT_DOMAIN_ERROR;",
            "",
            *gradient_declarations,
        ]
    )
    for flat_index, expression in enumerate(gradient_outputs):
        component, entry = divmod(flat_index, 4)
        lines.append(f"  temporary[{component}][{entry}] = {expression};")
    lines.extend(
        [
            "",
            "  for (size_t component = 0; component < KERR_EXACT_COMPONENT_COUNT;",
            "       ++component) {",
            "    for (size_t entry = 0; entry < 4; ++entry) {",
            "      if (!isfinite(temporary[component][entry]))",
            "        return KERR_EXACT_NONFINITE_RESULT;",
            "    }",
            "  }",
            "  for (size_t component = 0; component < KERR_EXACT_COMPONENT_COUNT;",
            "       ++component) {",
            "    results[component].value = temporary[component][0];",
            "    for (size_t axis = 0; axis < KERR_EXACT_DIMENSION; ++axis)",
            "      results[component].gradient[axis] = temporary[component][axis + 1];",
            "  }",
            "  return KERR_EXACT_SUCCESS;",
            "}",
            "",
            "double kerr_exact_throat_radius(void) {",
            "  return (2.0 + sqrt(3.0)) / 8.0;",
            "}",
            "",
            "const char *kerr_exact_component_name(kerr_exact_component component) {",
            "  static const char *const names[KERR_EXACT_COMPONENT_COUNT] = {",
            '      "tt", "tx", "ty", "tz", "xx",',
            '      "xy", "xz", "yy", "yz", "zz"};',
            "  if ((int)component < 0 ||",
            "      (int)component >= (int)KERR_EXACT_COMPONENT_COUNT)",
            "    return NULL;",
            "  return names[(size_t)component];",
            "}",
            "",
        ]
    )
    return "\n".join(lines)


def hexadecimal_double(expression: sp.Expr) -> str:
    """Round an 80-digit SymPy value to binary64 and emit it exactly."""

    return float(sp.N(expression, 80)).hex()


def generate_fixtures() -> str:
    """Generate high-precision reference fixtures for the C unit tests."""

    coordinates, values = build_metric()
    x, y, z = coordinates
    throat = (2 + sp.sqrt(3)) / 8
    points = (
        (sp.Integer(1), -sp.Rational(2, 3), sp.Rational(3, 4)),
        (sp.Rational(1, 10), -sp.Rational(1, 7), sp.Rational(1, 5)),
        (sp.Integer(0), sp.Integer(0), sp.Integer(1)),
        (sp.Integer(0), sp.Integer(0), -sp.Rational(3, 4)),
        (throat, sp.Integer(0), sp.Integer(0)),
        (throat * (1 - sp.Rational(1, 2**20)), sp.Integer(0), sp.Integer(0)),
        (throat * (1 + sp.Rational(1, 2**20)), sp.Integer(0), sp.Integer(0)),
    )
    gradients = tuple(
        tuple(sp.diff(value, coordinate) for coordinate in coordinates)
        for value in values
    )

    lines = [
        "/* Generated by generate_kerr_exact.py; do not edit manually. */",
        "#ifndef KERR_EXACT_FIXTURES_H",
        "#define KERR_EXACT_FIXTURES_H",
        "",
        "typedef struct kerr_exact_fixture {",
        "  double coordinate[3];",
        "  double value[KERR_EXACT_COMPONENT_COUNT];",
        "  double gradient[KERR_EXACT_COMPONENT_COUNT][3];",
        "} kerr_exact_fixture;",
        "",
        "static const kerr_exact_fixture kerr_exact_fixtures[] = {",
    ]
    for point in points:
        substitution = dict(zip(coordinates, point))
        fixture_values = [
            hexadecimal_double(value.subs(substitution)) for value in values
        ]
        fixture_gradients = [
            [hexadecimal_double(entry.subs(substitution)) for entry in gradient]
            for gradient in gradients
        ]
        lines.append("  {")
        lines.append(
            "    {" + ", ".join(hexadecimal_double(item) for item in point) + "},"
        )
        lines.append("    {" + ", ".join(fixture_values) + "},")
        lines.append("    {")
        for gradient in fixture_gradients:
            lines.append("      {" + ", ".join(gradient) + "},")
        lines.append("    }")
        lines.append("  },")
    lines.extend(
        [
            "};",
            "",
            "#define KERR_EXACT_FIXTURE_COUNT \\",
            "  (sizeof(kerr_exact_fixtures) / sizeof(kerr_exact_fixtures[0]))",
            "",
            "#endif /* KERR_EXACT_FIXTURES_H */",
            "",
        ]
    )
    return "\n".join(lines)


def parse_arguments() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="fail unless the committed generated source is current",
    )
    parser.add_argument(
        "--fixtures",
        type=Path,
        default=DEFAULT_FIXTURES,
        help="generated fixture-header destination",
    )
    parser.add_argument(
        "--output",
        type=Path,
        default=DEFAULT_OUTPUT,
        help="generated C destination (default: generated/kerr_exact.c)",
    )
    return parser.parse_args()


def main() -> int:
    arguments = parse_arguments()
    generated = generate_source()
    fixtures = generate_fixtures()
    destination = arguments.output.resolve()
    fixture_destination = arguments.fixtures.resolve()

    if arguments.check:
        for path, expected in (
            (destination, generated),
            (fixture_destination, fixtures),
        ):
            try:
                existing = path.read_text(encoding="utf-8")
            except FileNotFoundError:
                print(f"missing generated file: {path}", file=sys.stderr)
                return 1
            if existing != expected:
                difference = difflib.unified_diff(
                    existing.splitlines(),
                    expected.splitlines(),
                    fromfile=str(path),
                    tofile="freshly generated",
                    lineterm="",
                )
                print("\n".join(difference), file=sys.stderr)
                return 1
            print(f"generated file is current: {path}")
        return 0

    destination.parent.mkdir(parents=True, exist_ok=True)
    fixture_destination.parent.mkdir(parents=True, exist_ok=True)
    destination.write_text(generated, encoding="utf-8")
    fixture_destination.write_text(fixtures, encoding="utf-8")
    print(f"wrote {destination}")
    print(f"wrote {fixture_destination}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
