#!/usr/bin/env python3
"""Generate the fixed-parameter Cartesian Kerr ADM C evaluator and fixtures."""

from __future__ import annotations

import argparse
import difflib
from pathlib import Path
import sys

import sympy as sp


ROOT = Path(__file__).resolve().parent
DEFAULT_SOURCE = ROOT / "generated" / "kerr_adm_exact.c"
DEFAULT_FIXTURES = ROOT / "generated" / "kerr_adm_exact_fixtures.h"


def build_adm() -> tuple[tuple[sp.Symbol, ...], tuple[sp.Expr, ...]]:
    """Return coordinates and ten stable Cartesian ADM fields."""

    x, y, z = sp.symbols("x y z", real=True)
    radius_squared = x * x + y * y + z * z
    radius = sp.sqrt(radius_squared)

    mass = sp.Integer(1)
    spin = sp.Rational(1, 2)
    gap = sp.sqrt(3) / 2
    r_plus = mass + gap
    r_minus = spin**2 / r_plus
    throat = r_plus / 4

    p_factor = (radius - throat) ** 2 / radius
    q_factor = p_factor + 2 * gap
    boyer_radius = r_plus + p_factor
    sigma = boyer_radius**2 + spin**2 * z**2 / radius_squared
    cylindrical_squared = x * x + y * y
    a_factor = (
        sigma**2
        + spin**2
        * cylindrical_squared
        / radius_squared
        * (sigma + 2 * mass * boyer_radius)
    )
    ell = sigma / radius_squared
    dee = sigma * r_minus / (radius_squared * q_factor)
    cee = (
        spin**2
        * (sigma + 2 * mass * boyer_radius)
        / (sigma * radius_squared**2)
    )

    radial = sp.Matrix((x, y, z))
    azimuthal = sp.Matrix((-y, x, 0))
    gamma = (
        ell * sp.eye(3)
        + dee * radial * radial.T / radius_squared
        + cee * azimuthal * azimuthal.T
    )
    shift = sp.Matrix(
        (
            2 * mass * spin * boyer_radius * y / a_factor,
            -2 * mass * spin * boyer_radius * x / a_factor,
            0,
        )
    )

    # Retaining the sign of radius - throat gives the smooth lapse on the
    # doubled spatial slice.  Squaring it recovers the same four-metric lapse
    # function as the nonnegative convention.
    lapse = (radius - throat) * sp.sqrt(
        q_factor * sigma / (radius * a_factor)
    )
    fields = (
        lapse,
        shift[0],
        shift[1],
        shift[2],
        gamma[0, 0],
        gamma[0, 1],
        gamma[0, 2],
        gamma[1, 1],
        gamma[1, 2],
        gamma[2, 2],
    )
    return (x, y, z), fields


def c_expression(expression: sp.Expr) -> str:
    return sp.ccode(expression, standard="C99")


def emit_cse(
    expressions: tuple[sp.Expr, ...], prefix: str
) -> tuple[list[str], list[str]]:
    replacements, reduced = sp.cse(
        expressions, symbols=sp.numbered_symbols(prefix), order="canonical"
    )
    declarations = [
        f"  const double {symbol} = {c_expression(expression)};"
        for symbol, expression in replacements
    ]
    return declarations, [c_expression(expression) for expression in reduced]


def generate_source() -> str:
    coordinates, fields = build_adm()
    derivatives = tuple(
        sp.diff(field, coordinate)
        for field in fields
        for coordinate in coordinates
    )
    value_declarations, value_outputs = emit_cse(fields, "v")
    combined = tuple(
        item
        for field_index, field in enumerate(fields)
        for item in (field, *derivatives[3 * field_index : 3 * field_index + 3])
    )
    jet_declarations, jet_outputs = emit_cse(combined, "j")

    assert len(fields) == 10
    assert len(derivatives) == 30
    assert fields[3] == 0
    assert derivatives[9:12] == (0, 0, 0)
    for expression in (*fields, *derivatives):
        assert expression.free_symbols <= set(coordinates)
        assert not expression.has(sp.Derivative)

    lines = [
        "/*",
        " * Generated by generate_kerr_adm_exact.py; do not edit manually.",
        " * Fixed parameters: M=1, a=1/2; signed smooth LES lapse.",
        " */",
        '#include "kerr_adm_exact.h"',
        "",
        "#include <math.h>",
        "",
        "static int valid_coordinates(double x, double y, double z,",
        "                             double *radius) {",
        "  const double radius_squared = x * x + y * y + z * z;",
        "  if (!isfinite(x) || !isfinite(y) || !isfinite(z) ||",
        "      !isfinite(radius_squared) || radius_squared <= 0.0)",
        "    return 0;",
        "  *radius = sqrt(radius_squared);",
        "  return isfinite(*radius) && *radius > 0.0;",
        "}",
        "",
        "kerr_adm_exact_status kerr_adm_exact_values(",
        "    double x, double y, double z,",
        "    double values[KERR_ADM_FIELD_COUNT]) {",
        "  double radius;",
        "  double temporary[KERR_ADM_FIELD_COUNT];",
        "",
        "  if (values == NULL) return KERR_ADM_EXACT_INVALID_ARGUMENT;",
        "  if (!isfinite(x) || !isfinite(y) || !isfinite(z))",
        "    return KERR_ADM_EXACT_INVALID_ARGUMENT;",
        "  if (!valid_coordinates(x, y, z, &radius))",
        "    return KERR_ADM_EXACT_DOMAIN_ERROR;",
        "  (void)radius;",
        "",
        *value_declarations,
    ]
    lines.extend(
        f"  temporary[{index}] = {expression};"
        for index, expression in enumerate(value_outputs)
    )
    lines.extend(
        [
            "",
            "  for (size_t field = 0; field < KERR_ADM_FIELD_COUNT; ++field)",
            "    if (!isfinite(temporary[field]))",
            "      return KERR_ADM_EXACT_NONFINITE_RESULT;",
            "  for (size_t field = 0; field < KERR_ADM_FIELD_COUNT; ++field)",
            "    values[field] = temporary[field];",
            "  return KERR_ADM_EXACT_SUCCESS;",
            "}",
            "",
            "kerr_adm_exact_status kerr_adm_exact_value_gradient(",
            "    double x, double y, double z,",
            "    kerr_adm_value_gradient results[KERR_ADM_FIELD_COUNT]) {",
            "  double radius;",
            "  double temporary[KERR_ADM_FIELD_COUNT][4];",
            "  if (results == NULL) return KERR_ADM_EXACT_INVALID_ARGUMENT;",
            "  if (!isfinite(x) || !isfinite(y) || !isfinite(z))",
            "    return KERR_ADM_EXACT_INVALID_ARGUMENT;",
            "  if (!valid_coordinates(x, y, z, &radius))",
            "    return KERR_ADM_EXACT_DOMAIN_ERROR;",
            "  (void)radius;",
            "",
            *jet_declarations,
        ]
    )
    for index, expression in enumerate(jet_outputs):
        field, entry = divmod(index, 4)
        lines.append(f"  temporary[{field}][{entry}] = {expression};")
    lines.extend(
        [
            "",
            "  for (size_t field = 0; field < KERR_ADM_FIELD_COUNT; ++field)",
            "    for (size_t entry = 0; entry < 4; ++entry)",
            "      if (!isfinite(temporary[field][entry]))",
            "        return KERR_ADM_EXACT_NONFINITE_RESULT;",
            "  for (size_t field = 0; field < KERR_ADM_FIELD_COUNT; ++field) {",
            "    results[field].value = temporary[field][0];",
            "    for (size_t axis = 0; axis < KERR_ADM_DIMENSION; ++axis)",
            "      results[field].gradient[axis] = temporary[field][axis + 1];",
            "  }",
            "  return KERR_ADM_EXACT_SUCCESS;",
            "}",
            "",
            "double kerr_adm_exact_throat_radius(void) {",
            "  return (2.0 + sqrt(3.0)) / 8.0;",
            "}",
            "",
            "const char *kerr_adm_field_name(kerr_adm_field field) {",
            "  static const char *const names[KERR_ADM_FIELD_COUNT] = {",
            '      "alpha", "betax", "betay", "betaz", "gammaxx",',
            '      "gammaxy", "gammaxz", "gammayy", "gammayz", "gammazz"};',
            "  if ((int)field < 0 || (int)field >= KERR_ADM_FIELD_COUNT)",
            "    return NULL;",
            "  return names[(size_t)field];",
            "}",
            "",
        ]
    )
    return "\n".join(lines)


def hexadecimal_double(expression: sp.Expr) -> str:
    return float(sp.N(expression, 80)).hex()


def generate_fixtures() -> str:
    coordinates, fields = build_adm()
    x, y, z = coordinates
    throat = (2 + sp.sqrt(3)) / 8
    direction = (sp.Rational(2, 3), -sp.Rational(1, 3), sp.Rational(2, 3))
    points = (
        ("exterior", (sp.Integer(1), -sp.Rational(2, 3), sp.Rational(3, 4)), 1),
        ("inner", (sp.Rational(1, 10), -sp.Rational(1, 7), sp.Rational(1, 5)), 1),
        ("axis_plus", (0, 0, sp.Rational(3, 4)), 1),
        ("axis_minus", (0, 0, -sp.Rational(3, 4)), 1),
        ("throat", (throat, 0, 0), 1),
        (
            "throat_outside",
            tuple(throat * (1 + sp.Rational(1, 2**20)) * item for item in direction),
            1,
        ),
        (
            "throat_inside",
            tuple(throat * (1 - sp.Rational(1, 2**20)) * item for item in direction),
            1,
        ),
    )
    derivatives = tuple(
        sp.diff(field, coordinate)
        for field in fields
        for coordinate in coordinates
    )

    lines = [
        "/* Generated by generate_kerr_adm_exact.py; do not edit manually. */",
        "#ifndef KERR_ADM_EXACT_FIXTURES_H",
        "#define KERR_ADM_EXACT_FIXTURES_H",
        "",
        "typedef struct kerr_adm_exact_fixture {",
        "  const char *name;",
        "  double coordinate[3];",
        "  int has_gradient;",
        "  double value[KERR_ADM_FIELD_COUNT];",
        "  double gradient[KERR_ADM_FIELD_COUNT][KERR_ADM_DIMENSION];",
        "} kerr_adm_exact_fixture;",
        "",
        "static const kerr_adm_exact_fixture kerr_adm_exact_fixtures[] = {",
    ]
    for name, point, has_gradient in points:
        substitutions = dict(zip(coordinates, point))
        value_literals = [hexadecimal_double(field.subs(substitutions)) for field in fields]
        if has_gradient:
            gradient_literals = [
                hexadecimal_double(derivative.subs(substitutions))
                for derivative in derivatives
            ]
        else:
            gradient_literals = ["0x0.0p+0"] * len(derivatives)
        lines.extend(
            [
                "  {",
                f'    "{name}",',
                "    {" + ", ".join(hexadecimal_double(item) for item in point) + "},",
                f"    {has_gradient},",
                "    {" + ", ".join(value_literals) + "},",
                "    {",
            ]
        )
        for field in range(10):
            entries = gradient_literals[3 * field : 3 * field + 3]
            suffix = "," if field < 9 else ""
            lines.append("      {" + ", ".join(entries) + "}" + suffix)
        lines.extend(["    }", "  },"])
    lines.extend(
        [
            "};",
            "",
            "static const size_t kerr_adm_exact_fixture_count =",
            "    sizeof(kerr_adm_exact_fixtures) / sizeof(kerr_adm_exact_fixtures[0]);",
            "",
            "#endif /* KERR_ADM_EXACT_FIXTURES_H */",
            "",
        ]
    )
    return "\n".join(lines)


def check_or_write(path: Path, content: str, check: bool) -> bool:
    if check:
        try:
            existing = path.read_text(encoding="utf-8")
        except FileNotFoundError:
            print(f"missing generated file: {path}", file=sys.stderr)
            return False
        if existing == content:
            return True
        sys.stderr.writelines(
            difflib.unified_diff(
                existing.splitlines(keepends=True),
                content.splitlines(keepends=True),
                fromfile=str(path),
                tofile=f"{path} (regenerated)",
            )
        )
        return False
    path.write_text(content, encoding="utf-8")
    print(f"wrote {path.relative_to(ROOT)}")
    return True


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check", action="store_true", help="verify committed outputs byte-for-byte"
    )
    arguments = parser.parse_args()
    source = generate_source()
    fixtures = generate_fixtures()
    source_ok = check_or_write(DEFAULT_SOURCE, source, arguments.check)
    fixtures_ok = check_or_write(DEFAULT_FIXTURES, fixtures, arguments.check)
    if arguments.check and source_ok and fixtures_ok:
        print("generated Kerr ADM files are current")
    return 0 if source_ok and fixtures_ok else 1


if __name__ == "__main__":
    raise SystemExit(main())
